language: python
python:
  - "2.7"
    #  - "3.3"
    #- "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
    - export SLUGIFY_USES_TEXT_UNIDECODE=yes
    - pip install -e . 
    - pip install python-daemon==2.1.2
    - python setup.py build && python setup.py install --force
script:
  - py.test #--cov-report term-missing --cov app -v

